
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::MonoDevelop.Components.ConsoleView consoleview1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.consoleview1 = new global::MonoDevelop.Components.ConsoleView ();
		this.consoleview1.CanFocus = true;
		this.consoleview1.Name = "consoleview1";
		this.consoleview1.ShadowType = ((global::Gtk.ShadowType)(1));
		this.Add (this.consoleview1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
